# Generated by Django 4.2.2 on 2023-08-10 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_task_attach_file_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
